### ISSUE TITLE
Variable check fails on ansible_windows_domain_member

### ISSUE THREAD

**Issue by apiening** [justin-p/ansible-role-pdc#2]
I got the following error message:
```
failed: [testserver] (item=ansible_windows_domain_member) => changed=false
  ansible_loop_var: item
  assertion: ansible_windows_domain_member is defined
  evaluated_to: false
  item: ansible_windows_domain_member
  msg: Assertion failed
```

This variable is not set in the defaults and there is no explanation in the READE.md.
What is the meaning of this variable and what should I set it to?

**Comment by justin-p** [comment]
ansible_windows_domain_member is a variable that is normally set automatically by the fact gathering done by ansible, meaning you should not need to set this. 

You can read more about facts here. https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html

Try running the print debug example to show the current gathered facts. Recent version of ansible _might_ have changed something with that variable. Otherwise don't really have an idea from the top of my head and I'll have to look into it.

**Comment by justin-p** [comment]
Just tested the role in a clean environment using the following ansible version.
```
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/home/justinp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/justinp/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/justinp/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/justinp/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

Can't replicate the issue, if `ansible_windows_domain_member ` is not defined my main guess is that your fact gathering is either disabled or is unable to gather this information. Closing the issue for now.
